### PR TITLE
docs: fix url in handshake init

### PR DESCRIPTION
**Pull request by RCasatta**

### CODE REVIEW

**Comment by JamieDriver** [comment]
First commit is not wrong, it's just not necessary - that return value can be .../get_pin or .../set_pin depending on the state of the Jade (whether it currently has a wallet saved or not) and hence whether we need to get or set a PIN.  

Thanks for this - will merge to master asap.

**Comment by RCasatta** [comment]
Would you like I remove the first commit?

**Comment by JamieDriver** [comment]
Don't worry - I'll run the first two commits through the internal CI, and then merge.  Thanks mate.

**Comment by JamieDriver** [comment]
Merged @ de0d2528592ed269349bab1aebb425cd2a2ef270

**Pull request closed without merging**
