### PR TITLE
Add Functionality and Documentation for DIY Camera Builds

### PR DESCRIPTION
**Pull request by 3rdIteration**
1. Code changes to generalise camera support (Including tweaks to the menuconfig menus which you may want to change)
2. Generalise the IP5306 PMU as well (Previously was hardcoded to the M5Fire and Basic devices)
3. Add some options to enable a "Single Button UI" that basically just forces wrapping on every menu.
4. Config profiles for ESP32-CAM, ESP32-Wrover-CAM and T-Camera-Plus (All based around the "custom" device type)
5. Adjust profiles for M5Fire and M5Basic to use the full screen. (No scaling of elements or anything clever, just allowing the GUI window to take up the full space which spreads things out a bit)
6. Add hardware build documentation

The first item does touch a bit of code that is also used in the retail Jades, as well as make some changes that you might want to do differently in terms of menuconfig. Other than that the general approach has been to stick as closely as possible to the hardware found in the retail devices. (Everything seems to work quite nicely with the exception of the PinQR login workflow on T-Camera-Plus when on Battery and the ESP32-CAM, which may be power related but I haven't looked into it in too much depth)

Rather than just add endless profiles for component based builds, I just stuck with the "Custom" Jade type, expanded the functionality a bit and added some config profiles for three ESP32 boards that work quite well.

### CODE REVIEW

**Comment by JamieDriver** [comment]
Hey thanks for this.
I have tried to integrate this into our internal CI - I have pushed this: [diy_camera_jcd](https://github.com/Blockstream/Jade/tree/diy_camera_jcd).  I have made small changes and squashed commits etc. and pushed here.

The additional commit shows an issue - our ci runs the script `tools/check_default_configs.sh`and expects to see no diffs.  If it's just re-ordering it's easy enough to just check in the changes - but the changes here seem more significant.
I think its because the sdkconfig files as given are inconsistent with the menuconfig/Kconfig files ?

btw loving the 'full screen' m5stack devices ;-)

**Comment by 3rdIteration** [comment]
The fullscreen M5 stack is certainly nice and I am curious to play around with some options for a larger QR on those ones once this initial stuff is merged.

It all looks good and just gave it a quick test and it played nicely with an esp32-wrover-dev board, I can double check the other DIY hardware configs over the weekend as well. 

My only comment is that leaving some kind of console feedback for button presses is probably worthwhile when debug is enabled, at least when the hardware type is "custom", as otherwise it might be challenging for folk to troubleshoot their hardware assembly. (This wasn't really relevant for the previous DIY options)

**Comment by JamieDriver** [comment]
Do you think my branch version is good ?  
I was worried the `tools/check_default_configs.sh` had materially affected your defaults files - I guess the acid test is whether the final generated 'sdkconfig' file is any different.
I'll check that now - should have checked before (d'oh!)

**Comment by JamieDriver** [comment]
Ok, I have checked the generated sdkconfig files are indeed unchanged by the changes made to the defaults files - so that's all good.  Sorry for the noise.

I have pushed this branch to our internal CI so we'll see how it fares ... should be cool.
(I've put the changes it's hassling me to make into the separate commit, possibly for squashing later.)

Two thoughts really:
1. in all the places where we have 'HAS_CAMERA', are they all ok as just that ?  I'm thinking do any need to be 'HAS_CAMERA && HAS_PSRAM' ??     Jade devices not only have a camera they have 4Mb external ram, so the checks before on 'BOARD_TYPE_JADE[v1.1]' would have been implying camera *and* lots of ram.
It looks like the devices you've added all have camera and psram, so not a huge deal ... but I might make some tweaks to these ifdef checks in one or two places ... shouldn't affect the new devices.
If you're happy just leave it to me to make educated guesses!  (should anyone ever have a camera and low ram [if that even works!])
The main one I can think of is where it 'exports' a QR code for you to copy and scan back, but really I think all the places need a bit of consideration.

2. As much as I love the m5stack full-screen stuff maybe we need to hive that off into a separate PR, as will need a bit of an audit that all the screens look good (enough).  Maybe we want to make it a Kconfig option ?
(An advantage of having the m5 screen 'bordered' to look like a Jade screen is you can easily test UI changes on an m5stack knowing it will look the same on a jade proper/any-other-hw...)
I am a fan though - don't get me wrong!  ;-)
And I really appreciate the contributions mate - sorry it's taking so long to integrate.

**Comment by 3rdIteration** [comment]
Yea I checked the config files and it had mostly removed comments and other whitespace that I added.

In terms of your points
1. You are correct that there is no other check for the presence of psram, and you are right that I basically considered it implied in the code if you enable the feature. The camera initialization puts the framebuffer in psram, so it won't ever work unless folk are tweaking that code (and even then I couldn't get it to work without psram). If run without the psram, it at least visually throws an error when the user attempts to initialize the camera, rather than failing silently. (So basically it comes completely down to your preference as to how these kinds of dependencies are represented in the code)
2. Not a problem, easy to to and let people enable it themselves if they like without having to formally support it as a default :)

**Comment by 3rdIteration** [comment]
I saw the changes on the branch and it looks good, particularly switching things like the screen layout to relative rather than absolute, so well caught.

**Comment by JamieDriver** [comment]
Cool.
I'll try to get a colleague to also review and will look to get it merged.
Thanks.

**Comment by JamieDriver** [comment]
All good.  We're cutting a small release with some bugfixes and requested enhancements atm, and once that's tested, tagged and out the door this change will get merged to master.  Cheers.

**Comment by 3rdIteration** [comment]
No worries, no rush :)

**Comment by JamieDriver** [comment]
Apologies for the delay but this has now been merged to master.

Some other config-related changes [eg. update to base idf version, update to button lib] have also been merged - I do not have the devices you have added to check they are working as expected - if you could that'd be great.

If you're happy with my rebasing/merging of your stuff and it's working as you intended, we can close this PR.

Many thanks, as always.

**Comment by 3rdIteration** [comment]
Great, thanks :)

**Pull request closed without merging**
