### PR TITLE
Add M5StickC-Plus Support (+ Some fixes for M5Stack Basic)

### PR DESCRIPTION
**Pull request by 3rdIteration**
Was playing around with the repo as part of an upcoming series of YouTube videos for the Jade. I couldn't see any reason why the M5StickC-Plus wouldn't work so set about getting it going. Very impressed with the results, especially for a $20 USD device.

The major items included in the PR are:

M5StickC-Plus Support
- Added support for both basic wallet functions (Like M5Stack-Basic and TTGO T-Display)
- Added support for power management via AXP (Proper poweroff, battery/charging indicators, etc)
- Added device ID to JadePy
- Added note to build instructions about forcing baud rate lower (May also be applicable to other ESP32 hardware platforms)

Other General Fixes:
- Modified the default input behavior for the M5Stack-Basic as it has some issues that appear when used with Bluetooth active.
- Added config flag to persist USB pairings to NVS for all devices. (Originally I did this for DIY only, but see comment below)

### CODE REVIEW

**Comment by JamieDriver** [comment]
Thanks for this - we'll give it a look.  
Yes we had reports of the BLE issue and have pushed a new release to fix it - it was indeed an unintended bug.  (The config flag changed its default setting/behaviours if not explicitly set in esp-idf 5.0)

**Comment by 3rdIteration** [comment]
No worries, I'll remove the duplicate flags for that stuff shortly.

It also won't be a big deal to rework it and remove the external dependencies that were added if that is a preferred approach.

The only other thing that I am planning to add is a single page about DIY hardware options, just a basic overview.

**Comment by 3rdIteration** [comment]
So I have basically added some initial DIY docco as well fixing up the AXP192 stuff to be more suitable for production. 

Rather than duplicating it, the basic I2C functions that were previously defined for the Jade devices are now included based on a wider list of devices (Which includes the M5Stack Basic) and the AXP specific write command (basically just has the I2C address for the AXP fixed) was pulled out and is included based on the CONFIG_HAS_AXP. 

All the rest of the Jade specific stuff has been left untouched.

**Comment by JamieDriver** [comment]
Hey, this looks great.  I don't have a StickC to actually test with atm, but will try to get hold of one, but def 'concept-ack' from me.

Rather than merge the entire bag of commits, I'd suggest we squash them down to ~ 2 or 3, and in such an order that syncing to any commit is good and does not expose anything that doesn't work.
So eg. commit 1: the changes to the C code and any minimal config changes needed, 2. new StickC configs/kconfigs, docs etc., 3. all the other useful diy configs, images, additional docs, etc ?   Or something similar...

Many thanks for this work.

**Comment by 3rdIteration** [comment]
There were a few instances of messy overlap between the major blocks of work, so I just squashed it down to a single commit.

**Comment by JamieDriver** [comment]
Thanks,
I will rebase/merge this shortly once some other in-flight PRs/merges are done.
Assuming it's ok with you, I was going to remove the #ifdef section for M5StackBasic in `input.c`, and collapse it into the last case:
```
#else
...
void wheel_init(void)
{
    button_handle_t btn_handle_prev = iot_button_create(CONFIG_INPUT_BTN_A, BUTTON_ACTIVE_LOW);
    iot_button_set_evt_cb(btn_handle_prev, BUTTON_CB_PUSH, button_A_pressed, NULL);

    button_handle_t btn_handle_next = iot_button_create(CONFIG_INPUT_BTN_B, BUTTON_ACTIVE_LOW);
    iot_button_set_evt_cb(btn_handle_next, BUTTON_CB_PUSH, button_B_pressed, NULL);

    // M5Stack-Basic has three buttons, but the A button behaves behaves badly when Bluetooth is active.
    // In the case of the M5Stack-Basic, the A button generates constant input if serial input is enabled,
    // so the simplest fix is to remove the ability to hold the button down (ie do not add serial event handlers)
#if defined(CONFIG_ESP32_NO_BLOBS) || !defined(CONFIG_BOARD_TYPE_M5_BLACK_GRAY)
    iot_button_set_serial_cb(btn_handle_next, 1, 100 / portTICK_PERIOD_MS, button_B_pressed, NULL);
    iot_button_set_serial_cb(btn_handle_prev, 1, 100 / portTICK_PERIOD_MS, button_A_pressed, NULL);
#endif
}
```

Do you know if this only affects the 'basic' model, and not the 'fire' ?  (I'll dig some out and see what I can reproduce locally too).
I will ofc leave the commit under your name.

**Comment by 3rdIteration** [comment]
> Thanks, I will look to rebase/merge this shortly once some other in-flight PRs/merges are done - we only had one issue really - `diy/nodebug_configs` and `diy/secureboot_configs`: Can we replace these directories of configs with scripts (bash, sed, awk, py, anything ;-)) that convert the relevant base one from `configs/` ?? Or, worse case just some document describing how to make them ?
> 
> The reason being, that otherwise those configs soon become out-of-date and incorrect every time we update the esp-idf base, and we can't take on the maintenance overhead of keeping those files correct and up-to-date.
> 
> Also (ok, two issues! ;-)), assuming it's ok with you, I was going to remove the #ifdef section for M5StackBasic in `input.c`, and collapse it into the last case:
> 
> ```
> #else
> ...
> void wheel_init(void)
> {
>     button_handle_t btn_handle_prev = iot_button_create(CONFIG_INPUT_BTN_A, BUTTON_ACTIVE_LOW);
>     iot_button_set_evt_cb(btn_handle_prev, BUTTON_CB_PUSH, button_A_pressed, NULL);
> 
>     button_handle_t btn_handle_next = iot_button_create(CONFIG_INPUT_BTN_B, BUTTON_ACTIVE_LOW);
>     iot_button_set_evt_cb(btn_handle_next, BUTTON_CB_PUSH, button_B_pressed, NULL);
> 
>     // M5Stack-Basic/Fire hw has three buttons, but the A button behaves behaves badly when Bluetooth is active.
>     // In this case the A button generates constant input if serial input is enabled, so the simplest fix is to remove
>     // the ability to hold the button down (ie. do not add serial event handlers).
> #if defined(CONFIG_ESP32_NO_BLOBS) || (!defined(CONFIG_BOARD_TYPE_M5_BLACK_GRAY) && !defined(CONFIG_BOARD_TYPE_M5_FIRE))
>     iot_button_set_serial_cb(btn_handle_prev, 1, 100 / portTICK_PERIOD_MS, button_A_pressed, NULL);
>     iot_button_set_serial_cb(btn_handle_next, 1, 100 / portTICK_PERIOD_MS, button_B_pressed, NULL);
> #endif
> }
> ```
> 
> FYI: Issue affects M5Fire too, so slightly updated `#if` case. I will ofc leave the commit under your name. (We did get a report of this in the past and had this fix lurking about - we should have merged it before now - but since you've included it, it seems fairer to attribute the commit to your name.)

The DIY documentation covers the parts to add and remove, though, like the files this could quickly go out of date too. The neatest solution would probably be to handle it through a Python script which reads a reference sdkconfig.defaults file, takes the intended hardware-type and firmware-type as arguments and writes the sdkconfig.defaults directly. (The environment is already heavily python dependent, so easiest to just stick with something platform agnostic and use that)

**Comment by JamieDriver** [comment]
I'll get these other merges out the way, then I'll get this branch rebased and make the above tweaks - and I'll push it somewhere for final agreement (between you and I) before merging (and if you want to sign your commits etc. you can).

**Comment by JamieDriver** [comment]
Ok, I have pushed what I have made here - I hope the changes are acceptable to you.

a) if you are happy, let me know and I will merge that
b) If you want to make any further tweaks or want to sign your commits, do so in that branch or in this one in your fork, as is easier/preferable to you.
(I have to make sure any changes don't upset our internal CI processes before we put them in master, but that's no big deal.)
Really appreciate your effort/input!

**Comment by 3rdIteration** [comment]
Looks good, thanks for knocking up the python script.

The only thing that I noticed is that there were a few references to "BOARD_MOCK_SELECT_BUTTON" that I left in Kconfig.projbuild from when I was playing around with input methods.

**Comment by JamieDriver** [comment]
OK, updated: https://github.com/Blockstream/Jade/tree/stickC_pr

I ack your work here - if you are happy with my amendments, I will merge.  lmk.

**Comment by 3rdIteration** [comment]
Looks good :)

**Comment by JamieDriver** [comment]
Thanks.
btw appreciate the blog/video re: jade diy - v thorough!  ;-)

**Comment by JamieDriver** [comment]
Closing - merged to master from rebased branch at [f05e9225](https://gl.blockstream.io/blockstream/jade/-/commit/f05e922599e8a5e675a15560c643b4bbdc8ac802)

**Comment by 3rdIteration** [comment]
Just a heads up that I got a M5 Fire and tested it out. Basically the current issue is that it looks for ESP32_SPIRAM_SUPPORT, so that also needs to be removed from kconfig.projbuild. It was removed from all the Jade profiles and needs to be dropped for things to work with Fire.

This define is also checked in process.h in terms of liquid message size, so this should probably be removed across the board.

**Comment by JamieDriver** [comment]
I thought that was fixed in master already ?

**Pull request closed without merging**
