### PR TITLE
Add Functionality and Documentation for DIY Camera Builds

### PR DESCRIPTION
**Pull request by 3rdIteration**
1) Code changes to generalise camera support (Including tweaks to the menuconfig menus which you may want to change)
2) Generalise the IP5306 PMU as well (Previously was hardcoded to the M5Fire and Basic devices)
3) Add some options to enable a "Single Button UI" that basically just forces wrapping on every menu.
4) Config profiles for ESP32-CAM, ESP32-Wrover-CAM and T-Camera-Plus (All based around the "custom" device type) 
5) Add hardware build documentation

The first item does touch a bit of code that is also used in the retail Jades, as well as make some changes that you might want to do differently in terms of menuconfig. Other than that the general approach has been to stick as closely as possible to the hardware found in the retail devices. (Everything seems to work quite nicely with the exception of the PinQR login workflow on T-Camera-Plus when on Battery and the ESP32-CAM, which may be power related but I haven't looked into it in too much depth)

Rather than just add endless profiles for component based builds, I just stuck with the "Custom" Jade type, expanded the functionality a bit and added some config profiles for three ESP32 boards that work quite well.

### CODE REVIEW

**Comment by JamieDriver** [comment]
Hey - many thanks for this!
Will def look over it in detail but from a quick skim looks great.

> Add some options to enable a "Single Button UI" that basically just forces wrapping on every menu.

Yeah, FYI we may be adding wrapping by default on every screen/menu in any case, in an upcoming UI rewrite.

**Comment by 3rdIteration** [comment]
I just had an esp32-one show up, so will add that as well in the next week. (If it's usable)

**Comment by 3rdIteration** [comment]
> I just had an esp32-one show up, so will add that as well in the next week. (If it's usable)

So upon further inspection they have assigned the camera IO pins over the top of those needed by the display and some input buttons. :(

**Comment by JamieDriver** [comment]
Hey, sorry for the delay ... I've pushed a branch called `new_ui_wip` which if it passes our QA should get merged and released soon.  
Just a heads up if you're interested.  Cheers.

**Comment by 3rdIteration** [comment]
No worries, I'll check it out :)

**Comment by 3rdIteration** [comment]
Just a heads up that I'll go through and rebase this, remove any conflicts and check that everything is behaving as it ought

**Comment by JamieDriver** [comment]
Looks like it's pulled over a load of extra commits - prob want to checkout the branch and then `git rebase --onto master HEAD~2`or something similar ?

**Comment by 3rdIteration** [comment]
Stuck with browser only at the moment so I'll just close this one and bring a fresh PR

**Comment by JamieDriver** [comment]
Sorry mate - I can do that and push it back to your repo if you like - I just didn't want to take liberties !  ;-)

**Pull request closed without merging**
