### PR TITLE
Add M5Stack FIRE image and other readme improvements

### PR DESCRIPTION
**Pull request by epiccurious**
This PR does the following:
1. Add M5Stack FIRE image
2. Add mention of T-Display K164 variant with case from manufacture
3. Add alt text to DIY images for improved accessibility
4. Use product names from manufacturer
5. Fix broken 404 (case-sensitive) link from main `README.md` to `diy/README.md`

### CODE REVIEW

**Comment by epiccurious** [comment]
Recommend squashing commits.

**Comment by JamieDriver** [comment]
Thanks.  Another (earlier) 3rd-party PR already fixes the broken link.  
But many thanks for all this.
ack [0e6b777](https://github.com/Blockstream/Jade/pull/64/commits/0e6b77791dc4f929bc595fb37506ec709dfdf606)
Will rebase and merge after the imminent fw release.

**Comment by epiccurious** [comment]
Thanks Jamie. Would you like me to revert my fix for the 404 error?

**Comment by JamieDriver** [comment]
In a day or so I'll rebase, remove that commit if needed, and merge - assuming you're happy for me to do that ?
ofc all the commits will remain as they are and in your name etc.  (just might have my signature after the rebase).

**Comment by epiccurious** [comment]
I just noticed that M5Stack end-of-life'd the Core Basic v2.6 model in the link.

M5Stack updated the Core Basic hardware from v2.6 to v2.7, but the changes don't seem to affect Jade firmware:
> 2021.10
> Upgrade v2.7
> The screen was changed to a glass screen for clearer display;The Grove port adds a boost function to stabilize the 5.1V output with a more stable load;Add a battery-powered switch

The link should be updated. I'll add one more commit to update the url for the Core Basic model.

**Comment by epiccurious** [comment]
(FYI, the new URL contains a lower case "L" as in "lot" rather than lower case i as in "iot". This is a typo from M5Stack. The URL is still valid.)

**Comment by JamieDriver** [comment]
If it's good with you, will merge squashed, as per #66

**Comment by epiccurious** [comment]
Good with me. Thanks, Jamie.

**Comment by JamieDriver** [comment]
Thanks, #66 merged.  
Many thanks for your input - much appreciated.

**Pull request closed without merging**
